CREATE TABLE IF NOT EXISTS home_testimonials (
  id INT AUTO_INCREMENT PRIMARY KEY,
  video_url VARCHAR(255),
  thumbnail VARCHAR(255),
  text TEXT,
  avatar VARCHAR(255),
  name VARCHAR(255),
  subtitle VARCHAR(255),
  time VARCHAR(100),
  rating INT DEFAULT 5,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
