-- Table for Pricing FAQs
CREATE TABLE IF NOT EXISTS pricing_faqs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Table for Trusted Section
CREATE TABLE IF NOT EXISTS trusted_section (
  id INT AUTO_INCREMENT PRIMARY KEY,
  heading TEXT NOT NULL,
  avatar_images JSON NOT NULL,
  avatar_text TEXT NOT NULL,
  star_rating DECIMAL(3,2) DEFAULT 4.92,
  star_text TEXT NOT NULL,
  bottom_heading TEXT NOT NULL,
  bottom_text TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
